train:
    batch_size: 32
    test_batch_size: 10
    epochs: 5
    lr: 1.0
    gamma: 0.7
    no_cuda: False
    dry_run: False
    seed: 1
    log_interval: 10
    save_model: True
    path: checkpoints

inference:
    test_batch_size: 10
    no_cuda: False
    seed: 1
    path: checkpoints

